### PR TITLE
Update censys.go default virtual_hosts=EXCLUDE

### PR DESCRIPTION
**Pull request by 010blue**
When you use search.censys.io, you can see the default virtual_hosts var is EXCLUDE, it will ignore a lot of unwanted things.

### CODE REVIEW

**Comment by ehsandeep** [comment]
@010blue it was added on purpose - https://github.com/projectdiscovery/uncover/issues/81, what you mean by "it will ignore a lot of unwanted things"?

**Comment by 010blue** [comment]
I want to say that it is better to keep same as search.censys.io web, if you use censys in uncover to find ips via certs, you will get a lot of ips more than https://search.censys.io, but most of these ips are not accurate. @ehsandeep

**Comment by ehsandeep** [comment]
> I want to say that it is better to keep same as search.censys.io web, if you use censys in uncover to find ips via certs, you will get a lot of ips more than https://search.censys.io, but most of these ips are not accurate. @ehsandeep

@010blue do you have an example to share for this using uncover?

**Comment by 010blue** [comment]
I saw https://github.com/projectdiscovery/uncover/issues/81, maybe it's better that set virtual_hosts as a variable, let the users choose to use virtual_hosts=EXCLUDE, INCLUDE, or ONLY? For now it's a hardcode.

**Review by ehsandeep — CHANGES_REQUESTED** [review]
We can keep the default value as it is and allow it to update with `CENSYS_VIRTUAL_HOSTS` env variable.

**Comment by ehsandeep** [comment]
Closing due to inactivity.

**Pull request closed without merging**
